# Generated by Django 5.0.1 on 2024-01-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=255)),
                ('image_file', models.FileField(upload_to='images/')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sender_id', models.CharField(max_length=255)),
                ('receiver_id', models.CharField(max_length=255)),
                ('send_time', models.DateTimeField()),
                ('message_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=255)),
                ('text_post', models.TextField()),
                ('media_post', models.TextField()),
                ('id_user', models.CharField(max_length=255)),
                ('post_time', models.DateTimeField()),
                ('post_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('video_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
