# Generated by Django 5.0.1 on 2024-01-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_id_user_posts_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=255)),
                ('Voice_file', models.FileField(upload_to='voices/')),
                ('Vocie_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'voices',
            },
        ),
    ]
