# Generated by Django 5.0.1 on 2024-01-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_voice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='Vocie_url',
            new_name='vocie_url',
        ),
        migrations.RenameField(
            model_name='voice',
            old_name='Voice_file',
            new_name='voice_file',
        ),
    ]
