# Generated by Django 5.0.1 on 2024-01-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_vocie_url_voice_vocie_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='voice_duration',
            field=models.TextField(default='Default Title'),
        ),
    ]
