# Generated by Django 5.0.1 on 2024-01-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_message_voice_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_id',
            field=models.CharField(default='Default Id', max_length=255),
        ),
    ]
