# Generated by Django 5.0.1 on 2024-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_posts_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvtUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=255)),
                ('image_file', models.FileField(upload_to='avt_users/')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'avt_user',
            },
        ),
    ]
