# Generated by Django 5.0.1 on 2024-01-31 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_inforuser_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InforUser',
            new_name='InfoUser',
        ),
        migrations.AlterModelTable(
            name='infouser',
            table='info_user',
        ),
    ]
