# Generated by Django 5.0.1 on 2024-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_infouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('avt_url', models.TextField()),
                ('upload_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'info_user',
            },
        ),
        migrations.DeleteModel(
            name='AvtUser',
        ),
    ]
