# Generated by Django 5.0.1 on 2024-01-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_infouser_delete_avtuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
    ]
